### ISSUE TITLE
同步手机app数据 的SQL错误

### ISSUE THREAD

**Issue by Changchun-lin** [csdperic/csdp-support#52]
a:73)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:352)
        at ericsson.core.dao.BaseAppJdbcDao.executeBatchSql(BaseAppJdbcDao.java:576)
        at ericsson.csdp.web.ObjectWrite.SyncMoblieFTP.syncApproveList(SyncMoblieFTP.java:421)
        at ericsson.csdp.web.ObjectWrite.SyncMoblieFTP.sync(SyncMoblieFTP.java:349)
        at sun.reflect.GeneratedMethodAccessor338.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:321)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:111)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.sql.SQLException: Parameter index out of range (10 > number of parameters, which is 9).
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
        at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3288)
        at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3272)
        at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3314)
        at com.mysql.jdbc.PreparedStatement.setNull(PreparedStatement.java:3352)
        at com.mysql.jdbc.PreparedStatement.setObject(PreparedStatement.java:3522)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.setObject(DelegatingPreparedStatement.java:169)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.setObject(DelegatingPreparedStatement.java:169)
        at ericsson.core.dao.BaseAppJdbcDao$3.doInConnection(BaseAppJdbcDao.java:588)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:345)
        ... 11 more
2016-11-21 09:55:01,201 [startQuertz_Worker-9] INFO  [ericsson.csdp.web.ObjectWrite.SyncMoblieFTP]

**Comment by chulingchen** [comment]
已解决
